#!/bin/sh
#
# @name Generic Tilting
#
# @type Tilting Multirotor
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN6 motor 7
# @output MAIN6 motor 8
#
# @output AUX1 motor 1
# @output AUX2 motor 2
# @output AUX3 motor 3
# @output AUX4 motor 4
# @output AUX4 motor 5
# @output AUX4 motor 6
#
# @maintainer Salvatore Marcellini <salvatore.marcellini@gmail.com>
#

param set-default SYS_CTRL_ALLOC 1 #dynamic allocation
param set-default CA_AIRFRAME 12 #Tilting Multirotor

. ${R}etc/init.d/rc.mc_defaults
param set-default COM_FLTMODE1 8
param set-default COM_FLTMODE4 8
param set-default PWM_AUX_FUNC1 205
param set-default PWM_AUX_FUNC2 206
param set-default PWM_AUX_FUNC3 207
param set-default PWM_AUX_FUNC4 208
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 201
param set-default PWM_MAIN_FUNC6 202
param set-default PWM_MAIN_FUNC7 203
param set-default PWM_MAIN_FUNC8 204
param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MIN2 1100
param set-default PWM_MAIN_MIN3 1100
param set-default PWM_MAIN_MIN4 1100
param set-default MAV_TYPE 2 #Octorotor -- to change in case --

# Set all 8 channels
set PWM_OUT 12345678
set PWM_AUX_OUT 123456
